# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Sweety Sojrani
title: Graduate Student at San Jose State University
email: sweety.sojrani@sjsu.edu
# website: www.github.com/sproogen/resume-theme

# Social links
twitter_username: facespics
github_username:  sweetysojrani
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: in/sweetysojrani/
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I have more than 5 years of work experience on techno-functional roles as IT Developer, Business Analyst, Configuration Admin, Project Manager, and Mentor with IBM, Eaton and Pure Storage. Open for full time opportunities starting May-2020.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
more_title: Achievements
more_content: | # this will include new lines to allow paragraphs
   - Best project of the year award at Eaton for ‘Innovation’ and got 5/5 Customer Satisfaction Score for most of the projects
   - Received 16 E-star awards from Project Manager, Resource Manager, Project Sponsors at Eaton
   - Performed various PR activities as Vice President Public Relations of ‘Eaton Toastmasters Club’
   - Led the Eaton Cultural Committee ‘JOSH’ of successfully arranging  8 Cultural events at Eaton
   - Contributed 5 articles for ‘Eitchronicle’ quarterly magazine at Eaton for an audience of 75,000 employees
   - Taught basic Computer lessons to 8th grade underprivileged children of a local public School as part of Eaton CSR


# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
